databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: postgres
          property: username
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: RAILS_ENV
        value: production
